/*
* Copyright 2024 NXP
*
* SPDX-License-Identifier: BSD-3-Clause
*/
/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_AON_04 (coord B4), BUTTON */
/* Routed pin properties */
#define BOARD_INITPINS_BUTTON_PERIPHERAL                                  RGPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_BUTTON_SIGNAL                                     gpio_io   /*!< Signal name */
#define BOARD_INITPINS_BUTTON_CHANNEL                                         4U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_BUTTON_GPIO                                        RGPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_BUTTON_GPIO_PIN                                        4U   /*!< GPIO pin number */
#define BOARD_INITPINS_BUTTON_GPIO_PIN_MASK                           (1U << 4U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_08 (coord H5), USER_LED2 */
/* Routed pin properties */
#define BOARD_INITPINS_USER_LED2_PERIPHERAL                               RGPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_USER_LED2_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_USER_LED2_CHANNEL                                      8U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_USER_LED2_GPIO                                     RGPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_USER_LED2_GPIO_PIN                                     8U   /*!< GPIO pin number */
#define BOARD_INITPINS_USER_LED2_GPIO_PIN_MASK                        (1U << 8U)   /*!< GPIO pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);                    /* Function assigned for the Cortex-M33 */

/*!
 * @brief Configure MDIO Pins
 *
 */
void BOARD_ECAT_MDIO_InitPins(void);          /* Function assigned for the Cortex-M33 */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_Port0_RMII_InitPins(void);         /* Function assigned for the Cortex-M33 */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_Port1_RMII_InitPins(void);         /* Function assigned for the Cortex-M33 */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_ECAT_I2C_InitPins(void);           /* Function assigned for the Cortex-M33 */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_PHY_RST_InitPins(void);            /* Function assigned for the Cortex-M33 */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
