/*
* Copyright 2024 NXP
*
* SPDX-License-Identifier: BSD-3-Clause
*/
/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v14.0
processor: MIMXRT1189xxxxx
package_id: MIMXRT1189CVM8B
mcu_data: ksdk2_0
processor_version: 0.14.12
pin_labels:
- {pin_num: K15, pin_signal: GPIO_AD_21, label: M2_UDC, identifier: CUR_A;CUR_A2;M2_UDC}
- {pin_num: K12, pin_signal: GPIO_AD_22, label: M1_IDC, identifier: CUR_C;M1_IDC}
- {pin_num: N15, pin_signal: GPIO_AD_13, label: M2_IB, identifier: TP1;M2_IB}
- {pin_num: P17, pin_signal: GPIO_AD_12, label: TP119, identifier: TP2;M2_IA;TP119}
- {pin_num: B4, pin_signal: GPIO_AON_04, label: SW8, identifier: SW8}
- {pin_num: K3, pin_signal: GPIO_EMC_B1_06, label: USER_LED0, identifier: USER_LED0}
- {pin_num: M3, pin_signal: GPIO_EMC_B1_07, label: USER_LED1, identifier: USER_LED1}
- {pin_num: H5, pin_signal: GPIO_EMC_B1_08, label: USER_LED2, identifier: USER_LED2}
- {pin_num: E1, pin_signal: GPIO_EMC_B1_09, label: USER_LED3, identifier: USER_LED3}
- {pin_num: G6, pin_signal: GPIO_EMC_B1_12, label: M1_PWM_A0, identifier: M1_PWM_A0}
- {pin_num: F3, pin_signal: GPIO_EMC_B1_13, label: M1_PWM_B0, identifier: M1_PWM_B0}
- {pin_num: G5, pin_signal: GPIO_EMC_B1_14, label: M1_PWM_A1, identifier: M1_PWM_A1}
- {pin_num: G2, pin_signal: GPIO_EMC_B1_15, label: M1_PWM_B1, identifier: M1_PWM_B1}
- {pin_num: E2, pin_signal: GPIO_EMC_B1_17, label: M1_PWM_A2, identifier: M1_PWM_A2}
- {pin_num: H1, pin_signal: GPIO_EMC_B1_16, label: M1_PWM_B2, identifier: M1_PWM_B2}
- {pin_num: D1, pin_signal: GPIO_EMC_B1_18, label: M2_PWM_A0, identifier: M2_PWM_A0}
- {pin_num: F4, pin_signal: GPIO_EMC_B1_19, label: M2_PWM_B0, identifier: M2_PWM_B0}
- {pin_num: G1, pin_signal: GPIO_EMC_B1_20, label: M2_PWM_A1, identifier: M2_PWM_A1}
- {pin_num: K4, pin_signal: GPIO_EMC_B1_21, label: M2_PWM_B1, identifier: M2_PWM_B1}
- {pin_num: F1, pin_signal: GPIO_EMC_B1_23, label: M2_PWM_A2, identifier: M2_PWM_A2}
- {pin_num: L3, pin_signal: GPIO_EMC_B1_22, label: M2_PWM_B2, identifier: M2_PWM_B2}
- {pin_num: N14, pin_signal: GPIO_AD_14, label: M1_IA, identifier: M1_IA}
- {pin_num: N16, pin_signal: GPIO_AD_15, label: M1_IB, identifier: M1_IB}
- {pin_num: K16, pin_signal: GPIO_AD_18, label: M1_IC, identifier: M1_IC}
- {pin_num: L13, pin_signal: GPIO_AD_19, label: M1_UDC, identifier: M1_UDC}
- {pin_num: K13, pin_signal: GPIO_AD_20, label: M2_IC, identifier: M2_IC}
- {pin_num: K14, pin_signal: GPIO_AD_23, label: M2_IDC, identifier: M2_IDC}
- {pin_num: B15, pin_signal: GPIO_SD_B1_04, label: M1_GD3000_RESET, identifier: M1_GD3000_RESET}
- {pin_num: A16, pin_signal: GPIO_SD_B1_05, label: M1_GD3000_EN, identifier: M1_GD3000_EN}
- {pin_num: D5, pin_signal: GPIO_AON_19, label: M2_GD3000_RESET, identifier: M2_GD3000_RESET}
- {pin_num: E5, pin_signal: GPIO_AON_20, label: M2_GD3000_EN, identifier: M2_GD3000_EN}
- {pin_num: H3, pin_signal: GPIO_EMC_B1_00, label: M1_FAULT_OV, identifier: M1_FAULT_OC;M1_FAULT_OV}
- {pin_num: H4, pin_signal: GPIO_EMC_B1_01, label: M1_FAULT_OC, identifier: M1_FAULT_OC}
- {pin_num: N4, pin_signal: GPIO_EMC_B1_26, label: M1_FAULT_OT, identifier: M1_FAULT_OT}
- {pin_num: B13, pin_signal: GPIO_B1_04, label: M2_FAULT_OV, identifier: M2_FAULT_OV}
- {pin_num: J4, pin_signal: GPIO_EMC_B1_04, label: M2_FAULT_OV, identifier: M2_FAULT_OV}
- {pin_num: H6, pin_signal: GPIO_EMC_B1_05, label: M2_FAULT_OC, identifier: M2_FAULT_OC}
- {pin_num: E9, pin_signal: GPIO_B2_00, label: TP150, identifier: TP150}
- {pin_num: E10, pin_signal: GPIO_B2_01, label: TP151, identifier: TP151}
- {pin_num: F2, pin_signal: GPIO_EMC_B1_11, label: M2_485, identifier: M1_485;M2_485}
- {pin_num: E3, pin_signal: GPIO_EMC_B1_10, label: M1_485, identifier: M2_485;M1_485}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_xbar.h"
#include "fsl_iomuxc.h"
#include "fsl_rgpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 * 
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 * 
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void) {
    BOARD_InitPins();
    BOARD_InitADC();
    BOARD_InitPWM();
    BOARD_InitLPUART();
    BOARD_InitENC();
    BOARD_InitCMP();
    BOARD_InitLPSPI3();
    BOARD_InitLPSPI2();
    SINC_Motor1();
    SINC_Motor2();
    BOARD_UART5();
    BOARD_UART8();
    M7_DebugConsole();
    SLOWLOOP_TRIGGER();
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm7, enableClock: 'true'}
- pin_list:
  - {pin_num: K3, peripheral: RGPIO2, signal: 'gpio_io, 06', pin_signal: GPIO_EMC_B1_06, direction: OUTPUT}
  - {pin_num: M3, peripheral: RGPIO2, signal: 'gpio_io, 07', pin_signal: GPIO_EMC_B1_07, direction: OUTPUT}
  - {pin_num: E1, peripheral: RGPIO2, signal: 'gpio_io, 09', pin_signal: GPIO_EMC_B1_09, direction: OUTPUT}
  - {pin_num: E9, peripheral: RGPIO6, signal: 'gpio_io, 14', pin_signal: GPIO_B2_00, direction: OUTPUT}
  - {pin_num: E10, peripheral: RGPIO6, signal: 'gpio_io, 15', pin_signal: GPIO_B2_01, direction: OUTPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins, assigned for the Cortex-M7F core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc1);          /* Turn on LPCG: LPCG is ON. */

  /* GPIO configuration of USER_LED0 on GPIO_EMC_B1_06 (pin K3) */
  rgpio_pin_config_t USER_LED0_config = {
      .pinDirection = kRGPIO_DigitalOutput,
      .outputLogic = 0U,
  };
  /* Initialize GPIO functionality on GPIO_EMC_B1_06 (pin K3) */
  RGPIO_PinInit(RGPIO2, 6U, &USER_LED0_config);

  /* GPIO configuration of USER_LED1 on GPIO_EMC_B1_07 (pin M3) */
  rgpio_pin_config_t USER_LED1_config = {
      .pinDirection = kRGPIO_DigitalOutput,
      .outputLogic = 0U,
  };
  /* Initialize GPIO functionality on GPIO_EMC_B1_07 (pin M3) */
  RGPIO_PinInit(RGPIO2, 7U, &USER_LED1_config);

  /* GPIO configuration of USER_LED3 on GPIO_EMC_B1_09 (pin E1) */
  rgpio_pin_config_t USER_LED3_config = {
      .pinDirection = kRGPIO_DigitalOutput,
      .outputLogic = 0U,
  };
  /* Initialize GPIO functionality on GPIO_EMC_B1_09 (pin E1) */
  RGPIO_PinInit(RGPIO2, 9U, &USER_LED3_config);

  /* GPIO configuration of TP150 on GPIO_B2_00 (pin E9) */
  rgpio_pin_config_t TP150_config = {
      .pinDirection = kRGPIO_DigitalOutput,
      .outputLogic = 0U,
  };
  /* Initialize GPIO functionality on GPIO_B2_00 (pin E9) */
  RGPIO_PinInit(RGPIO6, 14U, &TP150_config);

  /* GPIO configuration of TP151 on GPIO_B2_01 (pin E10) */
  rgpio_pin_config_t TP151_config = {
      .pinDirection = kRGPIO_DigitalOutput,
      .outputLogic = 0U,
  };
  /* Initialize GPIO functionality on GPIO_B2_01 (pin E10) */
  RGPIO_PinInit(RGPIO6, 15U, &TP151_config);

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B2_00_GPIO6_IO14,           /* GPIO_B2_00 is configured as GPIO6_IO14 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B2_01_GPIO6_IO15,           /* GPIO_B2_01 is configured as GPIO6_IO15 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_06_GPIO2_IO06,       /* GPIO_EMC_B1_06 is configured as GPIO2_IO06 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_07_GPIO2_IO07,       /* GPIO_EMC_B1_07 is configured as GPIO2_IO07 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_09_GPIO2_IO09,       /* GPIO_EMC_B1_09 is configured as GPIO2_IO09 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitADC:
- options: {callFromInitBoot: 'true', coreID: cm7, enableClock: 'true'}
- pin_list:
  - {peripheral: ADC1, signal: 'HW_TRIG, 0', pin_signal: FLEXPWM4_PWM1_OUT_TRIG0_1}
  - {pin_num: N14, peripheral: ADC1, signal: 'A, 1_1', pin_signal: GPIO_AD_14, pull_keeper_select: Keeper}
  - {pin_num: N16, peripheral: ADC1, signal: 'B, 1_1', pin_signal: GPIO_AD_15, pull_keeper_select: Keeper}
  - {pin_num: P17, peripheral: ADC1, signal: 'A, 1_2', pin_signal: GPIO_AD_12, identifier: M2_IA, pull_keeper_select: Keeper}
  - {pin_num: N15, peripheral: ADC1, signal: 'B, 1_2', pin_signal: GPIO_AD_13, identifier: M2_IB, pull_keeper_select: Keeper}
  - {pin_num: K16, peripheral: ADC2, signal: 'A, 2_0', pin_signal: GPIO_AD_18, pull_keeper_select: Keeper}
  - {pin_num: L13, peripheral: ADC2, signal: 'B, 2_0', pin_signal: GPIO_AD_19, pull_keeper_select: Keeper}
  - {pin_num: K12, peripheral: ADC2, signal: 'A, 2_2', pin_signal: GPIO_AD_22, identifier: M1_IDC, pull_keeper_select: Keeper}
  - {pin_num: K13, peripheral: ADC2, signal: 'A, 2_1', pin_signal: GPIO_AD_20, pull_keeper_select: Keeper}
  - {pin_num: K15, peripheral: ADC2, signal: 'B, 2_1', pin_signal: GPIO_AD_21, identifier: M2_UDC, pull_keeper_select: Keeper}
  - {pin_num: K14, peripheral: ADC2, signal: 'B, 2_2', pin_signal: GPIO_AD_23, pull_keeper_select: Keeper}
  - {peripheral: ADC1, signal: 'HW_TRIG, 1', pin_signal: FLEXPWM2_PWM1_OUT_TRIG0_1}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitADC, assigned for the Cortex-M7F core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitADC(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc1);          /* Turn on LPCG: LPCG is ON. */
  CLOCK_EnableClock(kCLOCK_Xbar1);            /* Turn on LPCG: LPCG is ON. */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_12_GPIO4_IO12,           /* GPIO_AD_12 is configured as GPIO4_IO12 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_13_GPIO4_IO13,           /* GPIO_AD_13 is configured as GPIO4_IO13 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_14_GPIO4_IO14,           /* GPIO_AD_14 is configured as GPIO4_IO14 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_15_GPIO4_IO15,           /* GPIO_AD_15 is configured as GPIO4_IO15 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_18_GPIO4_IO18,           /* GPIO_AD_18 is configured as GPIO4_IO18 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_19_GPIO4_IO19,           /* GPIO_AD_19 is configured as GPIO4_IO19 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_20_GPIO4_IO20,           /* GPIO_AD_20 is configured as GPIO4_IO20 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_21_GPIO4_IO21,           /* GPIO_AD_21 is configured as GPIO4_IO21 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_22_GPIO4_IO22,           /* GPIO_AD_22 is configured as GPIO4_IO22 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_23_GPIO4_IO23,           /* GPIO_AD_23 is configured as GPIO4_IO23 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  XBAR_SetSignalsConnection(kXBAR1_InputFlexpwm4Pwm1OutTrig01, kXBAR1_OutputAdc12HwTrig0); /* FLEXPWM4_PWM1_OUT_TRIG0_1 output assigned to XBAR1_IN91 input is connected to XBAR1_OUT140 output assigned to ADC1_2_HW_TRIG0 */
  XBAR_SetSignalsConnection(kXBAR1_InputFlexpwm2Pwm1OutTrig01, kXBAR1_OutputAdc12HwTrig1); /* FLEXPWM2_PWM1_OUT_TRIG0_1 output assigned to XBAR1_IN83 input is connected to XBAR1_OUT141 output assigned to ADC1_2_HW_TRIG1 */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_12_GPIO4_IO12,           /* GPIO_AD_12 PAD functional properties : */
      0x0AU);                                 /* Slew Rate Field: Fast Slew Rate
                                                 Drive Strength Field: high driver
                                                 Pull / Keep Select Field: Pull Disable, Highz
                                                 Pull Up / Down Config. Field: Weak pull up
                                                 Open Drain Field: Disabled
                                                 Force ibe off Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_13_GPIO4_IO13,           /* GPIO_AD_13 PAD functional properties : */
      0x02U);                                 /* Slew Rate Field: Fast Slew Rate
                                                 Drive Strength Field: high driver
                                                 Pull / Keep Select Field: Pull Disable, Highz
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain Field: Disabled
                                                 Force ibe off Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_14_GPIO4_IO14,           /* GPIO_AD_14 PAD functional properties : */
      0x02U);                                 /* Slew Rate Field: Fast Slew Rate
                                                 Drive Strength Field: high driver
                                                 Pull / Keep Select Field: Pull Disable, Highz
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain Field: Disabled
                                                 Force ibe off Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_15_GPIO4_IO15,           /* GPIO_AD_15 PAD functional properties : */
      0x02U);                                 /* Slew Rate Field: Fast Slew Rate
                                                 Drive Strength Field: high driver
                                                 Pull / Keep Select Field: Pull Disable, Highz
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain Field: Disabled
                                                 Force ibe off Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_18_GPIO4_IO18,           /* GPIO_AD_18 PAD functional properties : */
      0x02U);                                 /* Slew Rate Field: Fast Slew Rate
                                                 Drive Strength Field: high driver
                                                 Pull / Keep Select Field: Pull Disable, Highz
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain Field: Disabled
                                                 Force ibe off Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_19_GPIO4_IO19,           /* GPIO_AD_19 PAD functional properties : */
      0x02U);                                 /* Slew Rate Field: Fast Slew Rate
                                                 Drive Strength Field: high driver
                                                 Pull / Keep Select Field: Pull Disable, Highz
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain Field: Disabled
                                                 Force ibe off Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_20_GPIO4_IO20,           /* GPIO_AD_20 PAD functional properties : */
      0x02U);                                 /* Slew Rate Field: Fast Slew Rate
                                                 Drive Strength Field: high driver
                                                 Pull / Keep Select Field: Pull Disable, Highz
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain Field: Disabled
                                                 Force ibe off Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_21_GPIO4_IO21,           /* GPIO_AD_21 PAD functional properties : */
      0x02U);                                 /* Slew Rate Field: Fast Slew Rate
                                                 Drive Strength Field: high driver
                                                 Pull / Keep Select Field: Pull Disable, Highz
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain Field: Disabled
                                                 Force ibe off Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_22_GPIO4_IO22,           /* GPIO_AD_22 PAD functional properties : */
      0x02U);                                 /* Slew Rate Field: Fast Slew Rate
                                                 Drive Strength Field: high driver
                                                 Pull / Keep Select Field: Pull Disable, Highz
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain Field: Disabled
                                                 Force Input Buffer Enable (IBE) off Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_23_GPIO4_IO23,           /* GPIO_AD_23 PAD functional properties : */
      0x02U);                                 /* Slew Rate Field: Fast Slew Rate
                                                 Drive Strength Field: high driver
                                                 Pull / Keep Select Field: Pull Disable, Highz
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain Field: Disabled
                                                 Force ibe off Field: Disabled */
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPWM:
- options: {callFromInitBoot: 'true', coreID: cm7, enableClock: 'true'}
- pin_list:
  - {pin_num: G6, peripheral: PWM4, signal: 'A, 0', pin_signal: GPIO_EMC_B1_12}
  - {pin_num: F3, peripheral: PWM4, signal: 'B, 0', pin_signal: GPIO_EMC_B1_13}
  - {pin_num: G5, peripheral: PWM4, signal: 'A, 1', pin_signal: GPIO_EMC_B1_14}
  - {pin_num: G2, peripheral: PWM4, signal: 'B, 1', pin_signal: GPIO_EMC_B1_15}
  - {pin_num: E2, peripheral: PWM4, signal: 'A, 2', pin_signal: GPIO_EMC_B1_17}
  - {pin_num: H1, peripheral: PWM4, signal: 'B, 2', pin_signal: GPIO_EMC_B1_16}
  - {pin_num: D1, peripheral: PWM2, signal: 'A, 0', pin_signal: GPIO_EMC_B1_18}
  - {pin_num: F4, peripheral: PWM2, signal: 'B, 0', pin_signal: GPIO_EMC_B1_19}
  - {pin_num: G1, peripheral: PWM2, signal: 'A, 1', pin_signal: GPIO_EMC_B1_20}
  - {pin_num: K4, peripheral: PWM2, signal: 'B, 1', pin_signal: GPIO_EMC_B1_21}
  - {pin_num: F1, peripheral: PWM2, signal: 'A, 2', pin_signal: GPIO_EMC_B1_23}
  - {pin_num: L3, peripheral: PWM2, signal: 'B, 2', pin_signal: GPIO_EMC_B1_22}
  - {pin_num: H3, peripheral: PWM4, signal: 'FAULT, 0', pin_signal: GPIO_EMC_B1_00, identifier: M1_FAULT_OV}
  - {pin_num: H4, peripheral: PWM4, signal: 'FAULT, 1', pin_signal: GPIO_EMC_B1_01}
  - {pin_num: N4, peripheral: PWM4, signal: 'FAULT, 2', pin_signal: GPIO_EMC_B1_26}
  - {pin_num: J4, peripheral: PWM2, signal: 'FAULT, 0', pin_signal: GPIO_EMC_B1_04}
  - {pin_num: H6, peripheral: PWM2, signal: 'FAULT, 1', pin_signal: GPIO_EMC_B1_05}
  - {peripheral: PWM2, signal: 'EXT_SYNC, 0', pin_signal: FLEXPWM4_PWM0_OUT_TRIG0_1}
  - {peripheral: PWM2, signal: 'EXT_SYNC, 1', pin_signal: FLEXPWM4_PWM0_OUT_TRIG0_1}
  - {peripheral: PWM2, signal: 'EXT_SYNC, 2', pin_signal: FLEXPWM4_PWM0_OUT_TRIG0_1}
  - {peripheral: PWM4, signal: FORCE, pin_signal: ECAT_SYNC_OUT0}
  - {peripheral: PWM2, signal: 'EXT_SYNC, 3', pin_signal: FLEXPWM4_PWM0_OUT_TRIG0_1}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPWM, assigned for the Cortex-M7F core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPWM(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc1);          /* Turn on LPCG: LPCG is ON. */
  CLOCK_EnableClock(kCLOCK_Xbar1);            /* Turn on LPCG: LPCG is ON. */

  BLK_CTRL_WAKEUPMIX->XBAR_DIR_CTRL1 = ((BLK_CTRL_WAKEUPMIX->XBAR_DIR_CTRL1 &
    (~(BLK_CTRL_WAKEUPMIX_XBAR_DIR_CTRL1_IOMUXC_XBAR_DIR_SEL_4_MASK | BLK_CTRL_WAKEUPMIX_XBAR_DIR_CTRL1_IOMUXC_XBAR_DIR_SEL_5_MASK | BLK_CTRL_WAKEUPMIX_XBAR_DIR_CTRL1_IOMUXC_XBAR_DIR_SEL_8_MASK | BLK_CTRL_WAKEUPMIX_XBAR_DIR_CTRL1_IOMUXC_XBAR_DIR_SEL_9_MASK | BLK_CTRL_WAKEUPMIX_XBAR_DIR_CTRL1_IOMUXC_XBAR_DIR_SEL_10_MASK))) /* Mask bits to zero which are setting */
      | BLK_CTRL_WAKEUPMIX_XBAR_DIR_CTRL1_IOMUXC_XBAR_DIR_SEL_4(0x00U) /* IOMUXC XBAR_INOUT4 function direction select: XBAR_INOUT as input */
      | BLK_CTRL_WAKEUPMIX_XBAR_DIR_CTRL1_IOMUXC_XBAR_DIR_SEL_5(0x00U) /* IOMUXC XBAR_INOUT5 function direction select: XBAR_INOUT as input */
      | BLK_CTRL_WAKEUPMIX_XBAR_DIR_CTRL1_IOMUXC_XBAR_DIR_SEL_8(0x00U) /* IOMUXC XBAR_INOUT8 function direction select: XBAR_INOUT as input */
      | BLK_CTRL_WAKEUPMIX_XBAR_DIR_CTRL1_IOMUXC_XBAR_DIR_SEL_9(0x00U) /* IOMUXC XBAR_INOUT9 function direction select: XBAR_INOUT as input */
      | BLK_CTRL_WAKEUPMIX_XBAR_DIR_CTRL1_IOMUXC_XBAR_DIR_SEL_10(0x00U) /* IOMUXC XBAR_INOUT10 function direction select: XBAR_INOUT as input */
    );
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_00_XBAR1_XBAR_INOUT04,  /* GPIO_EMC_B1_00 is configured as XBAR1_XBAR_INOUT04 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_01_XBAR1_XBAR_INOUT05,  /* GPIO_EMC_B1_01 is configured as XBAR1_XBAR_INOUT05 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_04_XBAR1_XBAR_INOUT08,  /* GPIO_EMC_B1_04 is configured as XBAR1_XBAR_INOUT08 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_05_XBAR1_XBAR_INOUT09,  /* GPIO_EMC_B1_05 is configured as XBAR1_XBAR_INOUT09 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_12_FLEXPWM4_PWMA00,  /* GPIO_EMC_B1_12 is configured as FLEXPWM4_PWMA00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_13_FLEXPWM4_PWMB00,  /* GPIO_EMC_B1_13 is configured as FLEXPWM4_PWMB00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_14_FLEXPWM4_PWMA01,  /* GPIO_EMC_B1_14 is configured as FLEXPWM4_PWMA01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_15_FLEXPWM4_PWMB01,  /* GPIO_EMC_B1_15 is configured as FLEXPWM4_PWMB01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_16_FLEXPWM4_PWMB02,  /* GPIO_EMC_B1_16 is configured as FLEXPWM4_PWMB02 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_17_FLEXPWM4_PWMA02,  /* GPIO_EMC_B1_17 is configured as FLEXPWM4_PWMA02 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_18_FLEXPWM2_PWMA00,  /* GPIO_EMC_B1_18 is configured as FLEXPWM2_PWMA00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_19_FLEXPWM2_PWMB00,  /* GPIO_EMC_B1_19 is configured as FLEXPWM2_PWMB00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_20_FLEXPWM2_PWMA01,  /* GPIO_EMC_B1_20 is configured as FLEXPWM2_PWMA01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_21_FLEXPWM2_PWMB01,  /* GPIO_EMC_B1_21 is configured as FLEXPWM2_PWMB01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_22_FLEXPWM2_PWMB02,  /* GPIO_EMC_B1_22 is configured as FLEXPWM2_PWMB02 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_23_FLEXPWM2_PWMA02,  /* GPIO_EMC_B1_23 is configured as FLEXPWM2_PWMA02 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_26_XBAR1_XBAR_INOUT10,  /* GPIO_EMC_B1_26 is configured as XBAR1_XBAR_INOUT10 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  XBAR_SetSignalsConnection(kXBAR1_InputIomuxXbarInout10, kXBAR1_OutputFlexpwm1234Fault2); /* IOMUX_XBAR_INOUT10 output assigned to XBAR1_IN10 input is connected to XBAR1_OUT53 output assigned to FLEXPWM1_2_3_4_FAULT2 */
  XBAR_SetSignalsConnection(kXBAR1_InputFlexpwm4Pwm0OutTrig01, kXBAR1_OutputFlexpwm2ExtSync0); /* FLEXPWM4_PWM0_OUT_TRIG0_1 output assigned to XBAR1_IN90 input is connected to XBAR1_OUT60 output assigned to FLEXPWM2_EXT_SYNC0 */
  XBAR_SetSignalsConnection(kXBAR1_InputFlexpwm4Pwm0OutTrig01, kXBAR1_OutputFlexpwm2ExtSync1); /* FLEXPWM4_PWM0_OUT_TRIG0_1 output assigned to XBAR1_IN90 input is connected to XBAR1_OUT61 output assigned to FLEXPWM2_EXT_SYNC1 */
  XBAR_SetSignalsConnection(kXBAR1_InputFlexpwm4Pwm0OutTrig01, kXBAR1_OutputFlexpwm2ExtSync2); /* FLEXPWM4_PWM0_OUT_TRIG0_1 output assigned to XBAR1_IN90 input is connected to XBAR1_OUT62 output assigned to FLEXPWM2_EXT_SYNC2 */
  XBAR_SetSignalsConnection(kXBAR1_InputFlexpwm4Pwm0OutTrig01, kXBAR1_OutputFlexpwm2ExtSync3); /* FLEXPWM4_PWM0_OUT_TRIG0_1 output assigned to XBAR1_IN90 input is connected to XBAR1_OUT63 output assigned to FLEXPWM2_EXT_SYNC3 */
  XBAR_SetSignalsConnection(kXBAR1_InputIomuxXbarInout08, kXBAR1_OutputFlexpwm2Fault0); /* IOMUX_XBAR_INOUT08 output assigned to XBAR1_IN8 input is connected to XBAR1_OUT65 output assigned to FLEXPWM2_FAULT0 */
  XBAR_SetSignalsConnection(kXBAR1_InputIomuxXbarInout09, kXBAR1_OutputFlexpwm2Fault1); /* IOMUX_XBAR_INOUT09 output assigned to XBAR1_IN9 input is connected to XBAR1_OUT66 output assigned to FLEXPWM2_FAULT1 */
  XBAR_SetSignalsConnection(kXBAR1_InputIomuxXbarInout04, kXBAR1_OutputFlexpwm4Fault0); /* IOMUX_XBAR_INOUT04 output assigned to XBAR1_IN4 input is connected to XBAR1_OUT84 output assigned to FLEXPWM4_FAULT0 */
  XBAR_SetSignalsConnection(kXBAR1_InputIomuxXbarInout05, kXBAR1_OutputFlexpwm4Fault1); /* IOMUX_XBAR_INOUT05 output assigned to XBAR1_IN5 input is connected to XBAR1_OUT85 output assigned to FLEXPWM4_FAULT1 */
  XBAR_SetSignalsConnection(kXBAR1_InputEcatSyncOut0, kXBAR1_OutputFlexpwm4ExtForce); /* ECAT_SYNC_OUT0 output assigned to XBAR1_IN214 input is connected to XBAR1_OUT86 output assigned to FLEXPWM4_EXT_FORCE */
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitLPUART:
- options: {callFromInitBoot: 'true', coreID: cm7, enableClock: 'true'}
- pin_list:
  - {pin_num: A5, peripheral: LPUART1, signal: RXD, pin_signal: GPIO_AON_09, pull_keeper_select: Keeper}
  - {pin_num: B1, peripheral: LPUART1, signal: TXD, pin_signal: GPIO_AON_08, pull_keeper_select: Keeper}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitLPUART, assigned for the Cortex-M7F core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitLPUART(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc2);          /* Turn on LPCG: LPCG is ON. */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AON_08_LPUART1_TX,          /* GPIO_AON_08 is configured as LPUART1_TX */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AON_09_LPUART1_RX,          /* GPIO_AON_09 is configured as LPUART1_RX */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AON_08_LPUART1_TX,          /* GPIO_AON_08 PAD functional properties : */
      0x02U);                                 /* Slew Rate Field: Fast Slew Rate
                                                 Drive Strength Field: high driver
                                                 Pull / Keep Select Field: Pull Disable, Highz
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AON_09_LPUART1_RX,          /* GPIO_AON_09 PAD functional properties : */
      0x02U);                                 /* Slew Rate Field: Fast Slew Rate
                                                 Drive Strength Field: high driver
                                                 Pull / Keep Select Field: Pull Disable, Highz
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain Field: Disabled */
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitENC:
- options: {callFromInitBoot: 'true', coreID: cm7, enableClock: 'true'}
- pin_list:
  - {pin_num: F5, peripheral: EQDC1, signal: 'PHASE, A', pin_signal: GPIO_EMC_B1_28}
  - {pin_num: E4, peripheral: EQDC1, signal: 'PHASE, B', pin_signal: GPIO_EMC_B1_29}
  - {pin_num: N5, peripheral: EQDC1, signal: INDEX, pin_signal: GPIO_EMC_B2_00}
  - {pin_num: N5, peripheral: EQDC1, signal: 'CAP, 1', pin_signal: GPIO_EMC_B2_00}
  - {pin_num: T5, peripheral: EQDC2, signal: 'PHASE, A', pin_signal: GPIO_EMC_B2_03}
  - {pin_num: P5, peripheral: EQDC2, signal: 'PHASE, B', pin_signal: GPIO_EMC_B2_02}
  - {pin_num: R2, peripheral: EQDC2, signal: INDEX, pin_signal: GPIO_EMC_B2_01}
  - {pin_num: R2, peripheral: EQDC2, signal: 'CAP, 1', pin_signal: GPIO_EMC_B2_01}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitENC, assigned for the Cortex-M7F core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitENC(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc1);          /* Turn on LPCG: LPCG is ON. */
  CLOCK_EnableClock(kCLOCK_Xbar1);            /* Turn on LPCG: LPCG is ON. */

  BLK_CTRL_WAKEUPMIX->XBAR_DIR_CTRL1 = ((BLK_CTRL_WAKEUPMIX->XBAR_DIR_CTRL1 &
    (~(BLK_CTRL_WAKEUPMIX_XBAR_DIR_CTRL1_IOMUXC_XBAR_DIR_SEL_12_MASK | BLK_CTRL_WAKEUPMIX_XBAR_DIR_CTRL1_IOMUXC_XBAR_DIR_SEL_13_MASK | BLK_CTRL_WAKEUPMIX_XBAR_DIR_CTRL1_IOMUXC_XBAR_DIR_SEL_20_MASK | BLK_CTRL_WAKEUPMIX_XBAR_DIR_CTRL1_IOMUXC_XBAR_DIR_SEL_21_MASK | BLK_CTRL_WAKEUPMIX_XBAR_DIR_CTRL1_IOMUXC_XBAR_DIR_SEL_22_MASK | BLK_CTRL_WAKEUPMIX_XBAR_DIR_CTRL1_IOMUXC_XBAR_DIR_SEL_23_MASK))) /* Mask bits to zero which are setting */
      | BLK_CTRL_WAKEUPMIX_XBAR_DIR_CTRL1_IOMUXC_XBAR_DIR_SEL_12(0x00U) /* IOMUXC XBAR_INOUT12 function direction select: XBAR_INOUT as input */
      | BLK_CTRL_WAKEUPMIX_XBAR_DIR_CTRL1_IOMUXC_XBAR_DIR_SEL_13(0x00U) /* IOMUXC XBAR_INOUT13 function direction select: XBAR_INOUT as input */
      | BLK_CTRL_WAKEUPMIX_XBAR_DIR_CTRL1_IOMUXC_XBAR_DIR_SEL_20(0x00U) /* IOMUXC XBAR_INOUT20 function direction select: XBAR_INOUT as input */
      | BLK_CTRL_WAKEUPMIX_XBAR_DIR_CTRL1_IOMUXC_XBAR_DIR_SEL_21(0x00U) /* IOMUXC XBAR_INOUT21 function direction select: XBAR_INOUT as input */
      | BLK_CTRL_WAKEUPMIX_XBAR_DIR_CTRL1_IOMUXC_XBAR_DIR_SEL_22(0x00U) /* IOMUXC XBAR_INOUT22 function direction select: XBAR_INOUT as input */
      | BLK_CTRL_WAKEUPMIX_XBAR_DIR_CTRL1_IOMUXC_XBAR_DIR_SEL_23(0x00U) /* IOMUXC XBAR_INOUT23 function direction select: XBAR_INOUT as input */
    );
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_28_XBAR1_XBAR_INOUT12,  /* GPIO_EMC_B1_28 is configured as XBAR1_XBAR_INOUT12 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_29_XBAR1_XBAR_INOUT13,  /* GPIO_EMC_B1_29 is configured as XBAR1_XBAR_INOUT13 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B2_00_XBAR1_XBAR_INOUT20,  /* GPIO_EMC_B2_00 is configured as XBAR1_XBAR_INOUT20 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B2_01_XBAR1_XBAR_INOUT21,  /* GPIO_EMC_B2_01 is configured as XBAR1_XBAR_INOUT21 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B2_02_XBAR1_XBAR_INOUT22,  /* GPIO_EMC_B2_02 is configured as XBAR1_XBAR_INOUT22 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B2_03_XBAR1_XBAR_INOUT23,  /* GPIO_EMC_B2_03 is configured as XBAR1_XBAR_INOUT23 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  XBAR_SetSignalsConnection(kXBAR1_InputIomuxXbarInout20, kXBAR1_OutputEqdc1Icap1); /* IOMUX_XBAR_INOUT20 output assigned to XBAR1_IN20 input is connected to XBAR1_OUT206 output assigned to EQDC1_ICAP1 */
  XBAR_SetSignalsConnection(kXBAR1_InputIomuxXbarInout21, kXBAR1_OutputEqdc2Icap1); /* IOMUX_XBAR_INOUT21 output assigned to XBAR1_IN21 input is connected to XBAR1_OUT209 output assigned to EQDC2_ICAP1 */
  XBAR_SetSignalsConnection(kXBAR1_InputIomuxXbarInout12, kXBAR1_OutputEqdc1Phasea); /* IOMUX_XBAR_INOUT12 output assigned to XBAR1_IN12 input is connected to XBAR1_OUT87 output assigned to EQDC1_PHASEA */
  XBAR_SetSignalsConnection(kXBAR1_InputIomuxXbarInout13, kXBAR1_OutputEqdc1Phaseb); /* IOMUX_XBAR_INOUT13 output assigned to XBAR1_IN13 input is connected to XBAR1_OUT88 output assigned to EQDC1_PHASEB */
  XBAR_SetSignalsConnection(kXBAR1_InputIomuxXbarInout20, kXBAR1_OutputEqdc1Index); /* IOMUX_XBAR_INOUT20 output assigned to XBAR1_IN20 input is connected to XBAR1_OUT89 output assigned to EQDC1_INDEX */
  XBAR_SetSignalsConnection(kXBAR1_InputIomuxXbarInout23, kXBAR1_OutputEqdc2Phasea); /* IOMUX_XBAR_INOUT23 output assigned to XBAR1_IN23 input is connected to XBAR1_OUT92 output assigned to EQDC2_PHASEA */
  XBAR_SetSignalsConnection(kXBAR1_InputIomuxXbarInout22, kXBAR1_OutputEqdc2Phaseb); /* IOMUX_XBAR_INOUT22 output assigned to XBAR1_IN22 input is connected to XBAR1_OUT93 output assigned to EQDC2_PHASEB */
  XBAR_SetSignalsConnection(kXBAR1_InputIomuxXbarInout21, kXBAR1_OutputEqdc2Index); /* IOMUX_XBAR_INOUT21 output assigned to XBAR1_IN21 input is connected to XBAR1_OUT94 output assigned to EQDC2_INDEX */
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitCMP:
- options: {callFromInitBoot: 'true', coreID: cm7, enableClock: 'true'}
- pin_list: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitCMP, assigned for the Cortex-M7F core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitCMP(void) {
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitLPSPI3:
- options: {callFromInitBoot: 'true', coreID: cm7, enableClock: 'true'}
- pin_list:
  - {pin_num: B16, peripheral: LPSPI3, signal: PCS0, pin_signal: GPIO_SD_B1_00}
  - {pin_num: D15, peripheral: LPSPI3, signal: SCK, pin_signal: GPIO_SD_B1_01}
  - {pin_num: D14, peripheral: LPSPI3, signal: SOUT, pin_signal: GPIO_SD_B1_02}
  - {pin_num: C15, peripheral: LPSPI3, signal: SIN, pin_signal: GPIO_SD_B1_03}
  - {pin_num: B15, peripheral: RGPIO5, signal: 'gpio_io, 08', pin_signal: GPIO_SD_B1_04, direction: OUTPUT, gpio_init_state: 'true', pull_down_pull_up_config: Pull_Forbidden}
  - {pin_num: A16, peripheral: RGPIO5, signal: 'gpio_io, 09', pin_signal: GPIO_SD_B1_05, direction: OUTPUT, gpio_init_state: 'false', pull_down_pull_up_config: Pull_Forbidden}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitLPSPI3, assigned for the Cortex-M7F core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitLPSPI3(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc1);          /* Turn on LPCG: LPCG is ON. */

  /* GPIO configuration of M1_GD3000_RESET on GPIO_SD_B1_04 (pin B15) */
  rgpio_pin_config_t M1_GD3000_RESET_config = {
      .pinDirection = kRGPIO_DigitalOutput,
      .outputLogic = 1U,
  };
  /* Initialize GPIO functionality on GPIO_SD_B1_04 (pin B15) */
  RGPIO_PinInit(RGPIO5, 8U, &M1_GD3000_RESET_config);

  /* GPIO configuration of M1_GD3000_EN on GPIO_SD_B1_05 (pin A16) */
  rgpio_pin_config_t M1_GD3000_EN_config = {
      .pinDirection = kRGPIO_DigitalOutput,
      .outputLogic = 0U,
  };
  /* Initialize GPIO functionality on GPIO_SD_B1_05 (pin A16) */
  RGPIO_PinInit(RGPIO5, 9U, &M1_GD3000_EN_config);

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B1_00_LPSPI3_PCS0,       /* GPIO_SD_B1_00 is configured as LPSPI3_PCS0 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B1_01_LPSPI3_SCK,        /* GPIO_SD_B1_01 is configured as LPSPI3_SCK */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B1_02_LPSPI3_SDO,        /* GPIO_SD_B1_02 is configured as LPSPI3_SDO */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B1_03_LPSPI3_SDI,        /* GPIO_SD_B1_03 is configured as LPSPI3_SDI */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B1_04_GPIO5_IO08,        /* GPIO_SD_B1_04 is configured as GPIO5_IO08 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B1_05_GPIO5_IO09,        /* GPIO_SD_B1_05 is configured as GPIO5_IO09 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_SD_B1_04_GPIO5_IO08,        /* GPIO_SD_B1_04 PAD functional properties : */
      0x00U);                                 /* PDRV Field: high driver
                                                 Pull Down Pull Up Field: Forbidden
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_SD_B1_05_GPIO5_IO09,        /* GPIO_SD_B1_05 PAD functional properties : */
      0x00U);                                 /* PDRV Field: high driver
                                                 Pull Down Pull Up Field: Forbidden
                                                 Open Drain Field: Disabled */
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitLPSPI2:
- options: {callFromInitBoot: 'true', coreID: cm7, enableClock: 'true'}
- pin_list:
  - {pin_num: D2, peripheral: LPSPI2, signal: PCS0, pin_signal: GPIO_AON_25}
  - {pin_num: C3, peripheral: LPSPI2, signal: SCK, pin_signal: GPIO_AON_22}
  - {pin_num: C1, peripheral: LPSPI2, signal: SIN, pin_signal: GPIO_AON_24}
  - {pin_num: C2, peripheral: LPSPI2, signal: SOUT, pin_signal: GPIO_AON_23}
  - {pin_num: D5, peripheral: RGPIO1, signal: 'gpio_io, 19', pin_signal: GPIO_AON_19, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: E5, peripheral: RGPIO1, signal: 'gpio_io, 20', pin_signal: GPIO_AON_20, direction: OUTPUT, gpio_init_state: 'false'}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitLPSPI2, assigned for the Cortex-M7F core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitLPSPI2(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc2);          /* Turn on LPCG: LPCG is ON. */

  /* GPIO configuration of M2_GD3000_RESET on IOMUXC_AON_SW_MUX_CTL_PAD_GPIO_AON_19 (pin D5) */
  rgpio_pin_config_t M2_GD3000_RESET_config = {
      .pinDirection = kRGPIO_DigitalOutput,
      .outputLogic = 1U,
  };
  /* Initialize GPIO functionality on IOMUXC_AON_SW_MUX_CTL_PAD_GPIO_AON_19 (pin D5) */
  RGPIO_PinInit(RGPIO1, 19U, &M2_GD3000_RESET_config);

  /* GPIO configuration of M2_GD3000_EN on IOMUXC_AON_SW_MUX_CTL_PAD_GPIO_AON_20 (pin E5) */
  rgpio_pin_config_t M2_GD3000_EN_config = {
      .pinDirection = kRGPIO_DigitalOutput,
      .outputLogic = 0U,
  };
  /* Initialize GPIO functionality on IOMUXC_AON_SW_MUX_CTL_PAD_GPIO_AON_20 (pin E5) */
  RGPIO_PinInit(RGPIO1, 20U, &M2_GD3000_EN_config);

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AON_19_GPIO1_IO19,          /* GPIO_AON_19 is configured as GPIO1_IO19 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AON_20_GPIO1_IO20,          /* GPIO_AON_20 is configured as GPIO1_IO20 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AON_22_LPSPI2_SCK,          /* GPIO_AON_22 is configured as LPSPI2_SCK */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AON_23_LPSPI2_SDO,          /* GPIO_AON_23 is configured as LPSPI2_SDO */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AON_24_LPSPI2_SDI,          /* GPIO_AON_24 is configured as LPSPI2_SDI */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AON_25_LPSPI2_PCS0,         /* GPIO_AON_25 is configured as LPSPI2_PCS0 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
SINC_Motor1:
- options: {callFromInitBoot: 'true', coreID: cm7, enableClock: 'true'}
- pin_list:
  - {pin_num: N12, peripheral: SINC1, signal: 'MOD_CLK, 0', pin_signal: GPIO_AD_00}
  - {pin_num: R14, peripheral: SINC1, signal: 'MOD_CLK, 1', pin_signal: GPIO_AD_01}
  - {pin_num: R13, peripheral: SINC1, signal: 'MOD_CLK, 2', pin_signal: GPIO_AD_02}
  - {pin_num: R15, peripheral: SINC1, signal: 'EMCLK, 0', pin_signal: GPIO_AD_03}
  - {pin_num: P15, peripheral: SINC1, signal: 'EMBIT, 0', pin_signal: GPIO_AD_04}
  - {pin_num: P13, peripheral: SINC1, signal: 'EMCLK, 1', pin_signal: GPIO_AD_05}
  - {pin_num: N13, peripheral: SINC1, signal: 'EMBIT, 1', pin_signal: GPIO_AD_06}
  - {pin_num: T17, peripheral: SINC1, signal: 'EMCLK, 2', pin_signal: GPIO_AD_07}
  - {pin_num: T14, peripheral: SINC1, signal: 'EMBIT, 2', pin_signal: GPIO_AD_08}
  - {pin_num: R16, peripheral: SINC1, signal: 'EMCLK, 3', pin_signal: GPIO_AD_09}
  - {pin_num: R17, peripheral: SINC1, signal: 'EMBIT, 3', pin_signal: GPIO_AD_10}
  - {peripheral: SINC1, signal: 'EXT_TRIG, 0', pin_signal: FLEXPWM4_PWM2_OUT_TRIG0_1}
  - {pin_num: P16, peripheral: SINC1, signal: sinc_break, pin_signal: GPIO_AD_11}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : SINC_Motor1, assigned for the Cortex-M7F core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void SINC_Motor1(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc1);          /* Turn on LPCG: LPCG is ON. */
  CLOCK_EnableClock(kCLOCK_Xbar1);            /* Turn on LPCG: LPCG is ON. */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_00_SINC1_MOD_CLK0,       /* GPIO_AD_00 is configured as SINC1_MOD_CLK0 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_01_SINC1_MOD_CLK1,       /* GPIO_AD_01 is configured as SINC1_MOD_CLK1 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_02_SINC1_MOD_CLK2,       /* GPIO_AD_02 is configured as SINC1_MOD_CLK2 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_03_SINC1_EMCLK00,        /* GPIO_AD_03 is configured as SINC1_EMCLK00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_04_SINC1_EMBIT00,        /* GPIO_AD_04 is configured as SINC1_EMBIT00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_05_SINC1_EMCLK01,        /* GPIO_AD_05 is configured as SINC1_EMCLK01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_06_SINC1_EMBIT01,        /* GPIO_AD_06 is configured as SINC1_EMBIT01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_07_SINC1_EMCLK02,        /* GPIO_AD_07 is configured as SINC1_EMCLK02 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_08_SINC1_EMBIT02,        /* GPIO_AD_08 is configured as SINC1_EMBIT02 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_09_SINC1_EMCLK03,        /* GPIO_AD_09 is configured as SINC1_EMCLK03 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_10_SINC1_EMBIT03,        /* GPIO_AD_10 is configured as SINC1_EMBIT03 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_11_SINC_FILTER_GLUE1_BREAK,  /* GPIO_AD_11 is configured as SINC_FILTER_GLUE1_BREAK */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  XBAR_SetSignalsConnection(kXBAR1_InputFlexpwm4Pwm2OutTrig01, kXBAR1_OutputSinc123ExtTrig0); /* FLEXPWM4_PWM2_OUT_TRIG0_1 output assigned to XBAR1_IN92 input is connected to XBAR1_OUT148 output assigned to SINC1_2_3_EXT_TRIG0 */
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
SINC_Motor2:
- options: {callFromInitBoot: 'true', coreID: cm7, enableClock: 'true'}
- pin_list:
  - {pin_num: M14, peripheral: SINC2, signal: 'EMCLK, 0', pin_signal: GPIO_AD_26}
  - {pin_num: M16, peripheral: SINC2, signal: 'EMBIT, 0', pin_signal: GPIO_AD_27}
  - {pin_num: L16, peripheral: SINC2, signal: 'EMCLK, 1', pin_signal: GPIO_AD_28}
  - {pin_num: L15, peripheral: SINC2, signal: 'EMBIT, 1', pin_signal: GPIO_AD_29}
  - {pin_num: L17, peripheral: SINC2, signal: 'EMCLK, 2', pin_signal: GPIO_AD_30}
  - {pin_num: K17, peripheral: SINC2, signal: 'EMBIT, 2', pin_signal: GPIO_AD_31}
  - {pin_num: J17, peripheral: SINC2, signal: 'EMCLK, 3', pin_signal: GPIO_AD_32}
  - {pin_num: J16, peripheral: SINC2, signal: 'EMBIT, 3', pin_signal: GPIO_AD_33}
  - {peripheral: SINC2, signal: 'EXT_TRIG, 1', pin_signal: FLEXPWM4_PWM2_OUT_TRIG0_1}
  - {pin_num: H17, peripheral: SINC2, signal: 'MOD_CLK, 0', pin_signal: GPIO_AD_35}
  - {pin_num: M13, peripheral: SINC2, signal: 'MOD_CLK, 1', pin_signal: GPIO_AD_24}
  - {pin_num: M15, peripheral: SINC2, signal: 'MOD_CLK, 2', pin_signal: GPIO_AD_25}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : SINC_Motor2, assigned for the Cortex-M7F core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void SINC_Motor2(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc1);          /* Turn on LPCG: LPCG is ON. */
  CLOCK_EnableClock(kCLOCK_Xbar1);            /* Turn on LPCG: LPCG is ON. */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_24_SINC2_MOD_CLK1,       /* GPIO_AD_24 is configured as SINC2_MOD_CLK1 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_25_SINC2_MOD_CLK2,       /* GPIO_AD_25 is configured as SINC2_MOD_CLK2 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_26_SINC2_EMCLK00,        /* GPIO_AD_26 is configured as SINC2_EMCLK00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_27_SINC2_EMBIT00,        /* GPIO_AD_27 is configured as SINC2_EMBIT00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_28_SINC2_EMCLK01,        /* GPIO_AD_28 is configured as SINC2_EMCLK01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_29_SINC2_EMBIT01,        /* GPIO_AD_29 is configured as SINC2_EMBIT01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_30_SINC2_EMCLK02,        /* GPIO_AD_30 is configured as SINC2_EMCLK02 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_31_SINC2_EMBIT02,        /* GPIO_AD_31 is configured as SINC2_EMBIT02 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_32_SINC2_EMCLK03,        /* GPIO_AD_32 is configured as SINC2_EMCLK03 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_33_SINC2_EMBIT03,        /* GPIO_AD_33 is configured as SINC2_EMBIT03 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_35_SINC2_MOD_CLK0,       /* GPIO_AD_35 is configured as SINC2_MOD_CLK0 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  XBAR_SetSignalsConnection(kXBAR1_InputFlexpwm4Pwm2OutTrig01, kXBAR1_OutputSinc123ExtTrig1); /* FLEXPWM4_PWM2_OUT_TRIG0_1 output assigned to XBAR1_IN92 input is connected to XBAR1_OUT149 output assigned to SINC1_2_3_EXT_TRIG1 */
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_UART5:
- options: {callFromInitBoot: 'true', coreID: cm7, enableClock: 'true'}
- pin_list:
  - {pin_num: F16, peripheral: LPUART5, signal: RXD, pin_signal: GPIO_SD_B2_09}
  - {pin_num: F14, peripheral: LPUART5, signal: TXD, pin_signal: GPIO_SD_B2_08}
  - {pin_num: E3, peripheral: RGPIO2, signal: 'gpio_io, 10', pin_signal: GPIO_EMC_B1_10, identifier: M1_485, direction: OUTPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_UART5, assigned for the Cortex-M7F core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_UART5(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc1);          /* Turn on LPCG: LPCG is ON. */

  /* GPIO configuration of M1_485 on GPIO_EMC_B1_10 (pin E3) */
  rgpio_pin_config_t M1_485_config = {
      .pinDirection = kRGPIO_DigitalOutput,
      .outputLogic = 0U,
  };
  /* Initialize GPIO functionality on GPIO_EMC_B1_10 (pin E3) */
  RGPIO_PinInit(RGPIO2, 10U, &M1_485_config);

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_10_GPIO2_IO10,       /* GPIO_EMC_B1_10 is configured as GPIO2_IO10 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B2_08_LPUART5_TX,        /* GPIO_SD_B2_08 is configured as LPUART5_TX */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B2_09_LPUART5_RX,        /* GPIO_SD_B2_09 is configured as LPUART5_RX */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_UART8:
- options: {callFromInitBoot: 'true', coreID: cm7, enableClock: 'true'}
- pin_list:
  - {pin_num: H14, peripheral: LPUART8, signal: RXD, pin_signal: GPIO_SD_B2_01}
  - {pin_num: H15, peripheral: LPUART8, signal: TXD, pin_signal: GPIO_SD_B2_00}
  - {pin_num: F2, peripheral: RGPIO2, signal: 'gpio_io, 11', pin_signal: GPIO_EMC_B1_11, identifier: M2_485, direction: OUTPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_UART8, assigned for the Cortex-M7F core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_UART8(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc1);          /* Turn on LPCG: LPCG is ON. */

  /* GPIO configuration of M2_485 on GPIO_EMC_B1_11 (pin F2) */
  rgpio_pin_config_t M2_485_config = {
      .pinDirection = kRGPIO_DigitalOutput,
      .outputLogic = 0U,
  };
  /* Initialize GPIO functionality on GPIO_EMC_B1_11 (pin F2) */
  RGPIO_PinInit(RGPIO2, 11U, &M2_485_config);

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_11_GPIO2_IO11,       /* GPIO_EMC_B1_11 is configured as GPIO2_IO11 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B2_00_LPUART8_TX,        /* GPIO_SD_B2_00 is configured as LPUART8_TX */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B2_01_LPUART8_RX,        /* GPIO_SD_B2_01 is configured as LPUART8_RX */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
M7_DebugConsole:
- options: {callFromInitBoot: 'true', coreID: cm7, enableClock: 'true'}
- pin_list:
  - {pin_num: K2, peripheral: LPUART3, signal: RXD, pin_signal: GPIO_EMC_B1_02}
  - {pin_num: G3, peripheral: LPUART3, signal: TXD, pin_signal: GPIO_EMC_B1_03}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : M7_DebugConsole, assigned for the Cortex-M7F core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void M7_DebugConsole(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc1);          /* Turn on LPCG: LPCG is ON. */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_02_LPUART3_RX,       /* GPIO_EMC_B1_02 is configured as LPUART3_RX */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_03_LPUART3_TX,       /* GPIO_EMC_B1_03 is configured as LPUART3_TX */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
SLOWLOOP_TRIGGER:
- options: {callFromInitBoot: 'true', coreID: cm7, enableClock: 'true'}
- pin_list:
  - {peripheral: TMR1, signal: 'TIMER_INPUT, 0', pin_signal: ECAT_SYNC_OUT0}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : SLOWLOOP_TRIGGER, assigned for the Cortex-M7F core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void SLOWLOOP_TRIGGER(void) {
  CLOCK_EnableClock(kCLOCK_Xbar1);            /* Turn on LPCG: LPCG is ON. */

  BLK_CTRL_WAKEUPMIX->QTIMER_CTRL1 = ((BLK_CTRL_WAKEUPMIX->QTIMER_CTRL1 &
    (~(BLK_CTRL_WAKEUPMIX_QTIMER_CTRL1_QTIMER1_TMR0_INPUT_SEL_MASK))) /* Mask bits to zero which are setting */
      | BLK_CTRL_WAKEUPMIX_QTIMER_CTRL1_QTIMER1_TMR0_INPUT_SEL(0x01U) /* QTIMER1 TMR0 input select: Input from XBAR */
    );
  XBAR_SetSignalsConnection(kXBAR1_InputEcatSyncOut0, kXBAR1_OutputQtimer1Timer0); /* ECAT_SYNC_OUT0 output assigned to XBAR1_IN214 input is connected to XBAR1_OUT107 output assigned to QTIMER1_TIMER0 */
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
