/*
* Copyright 2024 NXP
*
* SPDX-License-Identifier: BSD-3-Clause
*/
/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_EMC_B1_06 (coord K3), USER_LED0 */
/* Routed pin properties */
#define BOARD_INITPINS_USER_LED0_PERIPHERAL                               RGPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_USER_LED0_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_USER_LED0_CHANNEL                                      6U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_USER_LED0_GPIO                                     RGPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_USER_LED0_GPIO_PIN                                     6U   /*!< GPIO pin number */
#define BOARD_INITPINS_USER_LED0_GPIO_PIN_MASK                        (1U << 6U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_07 (coord M3), USER_LED1 */
/* Routed pin properties */
#define BOARD_INITPINS_USER_LED1_PERIPHERAL                               RGPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_USER_LED1_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_USER_LED1_CHANNEL                                      7U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_USER_LED1_GPIO                                     RGPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_USER_LED1_GPIO_PIN                                     7U   /*!< GPIO pin number */
#define BOARD_INITPINS_USER_LED1_GPIO_PIN_MASK                        (1U << 7U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_09 (coord E1), USER_LED3 */
/* Routed pin properties */
#define BOARD_INITPINS_USER_LED3_PERIPHERAL                               RGPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_USER_LED3_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_USER_LED3_CHANNEL                                      9U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_USER_LED3_GPIO                                     RGPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_USER_LED3_GPIO_PIN                                     9U   /*!< GPIO pin number */
#define BOARD_INITPINS_USER_LED3_GPIO_PIN_MASK                        (1U << 9U)   /*!< GPIO pin mask */

/* GPIO_B2_00 (coord E9), TP150 */
/* Routed pin properties */
#define BOARD_INITPINS_TP150_PERIPHERAL                                   RGPIO6   /*!< Peripheral name */
#define BOARD_INITPINS_TP150_SIGNAL                                      gpio_io   /*!< Signal name */
#define BOARD_INITPINS_TP150_CHANNEL                                         14U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_TP150_GPIO                                         RGPIO6   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_TP150_GPIO_PIN                                        14U   /*!< GPIO pin number */
#define BOARD_INITPINS_TP150_GPIO_PIN_MASK                           (1U << 14U)   /*!< GPIO pin mask */

/* GPIO_B2_01 (coord E10), TP151 */
/* Routed pin properties */
#define BOARD_INITPINS_TP151_PERIPHERAL                                   RGPIO6   /*!< Peripheral name */
#define BOARD_INITPINS_TP151_SIGNAL                                      gpio_io   /*!< Signal name */
#define BOARD_INITPINS_TP151_CHANNEL                                         15U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_TP151_GPIO                                         RGPIO6   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_TP151_GPIO_PIN                                        15U   /*!< GPIO pin number */
#define BOARD_INITPINS_TP151_GPIO_PIN_MASK                           (1U << 15U)   /*!< GPIO pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);                    /* Function assigned for the Cortex-M7F */

/* GPIO_AD_14 (coord N14), M1_IA */
/* Routed pin properties */
#define BOARD_INITADC_M1_IA_PERIPHERAL                                      ADC1   /*!< Peripheral name */
#define BOARD_INITADC_M1_IA_SIGNAL                                             A   /*!< Signal name */
#define BOARD_INITADC_M1_IA_CHANNEL                                           1U   /*!< Signal channel */

/* GPIO_AD_15 (coord N16), M1_IB */
/* Routed pin properties */
#define BOARD_INITADC_M1_IB_PERIPHERAL                                      ADC1   /*!< Peripheral name */
#define BOARD_INITADC_M1_IB_SIGNAL                                             B   /*!< Signal name */
#define BOARD_INITADC_M1_IB_CHANNEL                                           1U   /*!< Signal channel */

/* GPIO_AD_12 (coord P17), TP119 */
/* Routed pin properties */
#define BOARD_INITADC_M2_IA_PERIPHERAL                                      ADC1   /*!< Peripheral name */
#define BOARD_INITADC_M2_IA_SIGNAL                                             A   /*!< Signal name */
#define BOARD_INITADC_M2_IA_CHANNEL                                           1U   /*!< Signal channel */

/* GPIO_AD_13 (coord N15), M2_IB */
/* Routed pin properties */
#define BOARD_INITADC_M2_IB_PERIPHERAL                                      ADC1   /*!< Peripheral name */
#define BOARD_INITADC_M2_IB_SIGNAL                                             B   /*!< Signal name */
#define BOARD_INITADC_M2_IB_CHANNEL                                           1U   /*!< Signal channel */

/* GPIO_AD_18 (coord K16), M1_IC */
/* Routed pin properties */
#define BOARD_INITADC_M1_IC_PERIPHERAL                                      ADC2   /*!< Peripheral name */
#define BOARD_INITADC_M1_IC_SIGNAL                                             A   /*!< Signal name */
#define BOARD_INITADC_M1_IC_CHANNEL                                           2U   /*!< Signal channel */

/* GPIO_AD_19 (coord L13), M1_UDC */
/* Routed pin properties */
#define BOARD_INITADC_M1_UDC_PERIPHERAL                                     ADC2   /*!< Peripheral name */
#define BOARD_INITADC_M1_UDC_SIGNAL                                            B   /*!< Signal name */
#define BOARD_INITADC_M1_UDC_CHANNEL                                          2U   /*!< Signal channel */

/* GPIO_AD_22 (coord K12), M1_IDC */
/* Routed pin properties */
#define BOARD_INITADC_M1_IDC_PERIPHERAL                                     ADC2   /*!< Peripheral name */
#define BOARD_INITADC_M1_IDC_SIGNAL                                            A   /*!< Signal name */
#define BOARD_INITADC_M1_IDC_CHANNEL                                          2U   /*!< Signal channel */

/* GPIO_AD_20 (coord K13), M2_IC */
/* Routed pin properties */
#define BOARD_INITADC_M2_IC_PERIPHERAL                                      ADC2   /*!< Peripheral name */
#define BOARD_INITADC_M2_IC_SIGNAL                                             A   /*!< Signal name */
#define BOARD_INITADC_M2_IC_CHANNEL                                           2U   /*!< Signal channel */

/* GPIO_AD_21 (coord K15), M2_UDC */
/* Routed pin properties */
#define BOARD_INITADC_M2_UDC_PERIPHERAL                                     ADC2   /*!< Peripheral name */
#define BOARD_INITADC_M2_UDC_SIGNAL                                            B   /*!< Signal name */
#define BOARD_INITADC_M2_UDC_CHANNEL                                          2U   /*!< Signal channel */

/* GPIO_AD_23 (coord K14), M2_IDC */
/* Routed pin properties */
#define BOARD_INITADC_M2_IDC_PERIPHERAL                                     ADC2   /*!< Peripheral name */
#define BOARD_INITADC_M2_IDC_SIGNAL                                            B   /*!< Signal name */
#define BOARD_INITADC_M2_IDC_CHANNEL                                          2U   /*!< Signal channel */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitADC(void);                     /* Function assigned for the Cortex-M7F */

#define XBAR_DIR_CTRL1_IOMUXC_XBAR_DIR_SEL_10_IOMUX 0x00U /*!< IOMUXC XBAR_INOUT10 function direction select: XBAR_INOUT as input */
#define XBAR_DIR_CTRL1_IOMUXC_XBAR_DIR_SEL_4_IOMUX 0x00U /*!< IOMUXC XBAR_INOUT4 function direction select: XBAR_INOUT as input */
#define XBAR_DIR_CTRL1_IOMUXC_XBAR_DIR_SEL_5_IOMUX 0x00U /*!< IOMUXC XBAR_INOUT5 function direction select: XBAR_INOUT as input */
#define XBAR_DIR_CTRL1_IOMUXC_XBAR_DIR_SEL_8_IOMUX 0x00U /*!< IOMUXC XBAR_INOUT8 function direction select: XBAR_INOUT as input */
#define XBAR_DIR_CTRL1_IOMUXC_XBAR_DIR_SEL_9_IOMUX 0x00U /*!< IOMUXC XBAR_INOUT9 function direction select: XBAR_INOUT as input */

/* GPIO_EMC_B1_12 (coord G6), M1_PWM_A0 */
/* Routed pin properties */
#define BOARD_INITPWM_M1_PWM_A0_PERIPHERAL                                  PWM4   /*!< Peripheral name */
#define BOARD_INITPWM_M1_PWM_A0_SIGNAL                                         A   /*!< Signal name */
#define BOARD_INITPWM_M1_PWM_A0_CHANNEL                                       0U   /*!< Signal channel */

/* GPIO_EMC_B1_13 (coord F3), M1_PWM_B0 */
/* Routed pin properties */
#define BOARD_INITPWM_M1_PWM_B0_PERIPHERAL                                  PWM4   /*!< Peripheral name */
#define BOARD_INITPWM_M1_PWM_B0_SIGNAL                                         B   /*!< Signal name */
#define BOARD_INITPWM_M1_PWM_B0_CHANNEL                                       0U   /*!< Signal channel */

/* GPIO_EMC_B1_14 (coord G5), M1_PWM_A1 */
/* Routed pin properties */
#define BOARD_INITPWM_M1_PWM_A1_PERIPHERAL                                  PWM4   /*!< Peripheral name */
#define BOARD_INITPWM_M1_PWM_A1_SIGNAL                                         A   /*!< Signal name */
#define BOARD_INITPWM_M1_PWM_A1_CHANNEL                                       1U   /*!< Signal channel */

/* GPIO_EMC_B1_15 (coord G2), M1_PWM_B1 */
/* Routed pin properties */
#define BOARD_INITPWM_M1_PWM_B1_PERIPHERAL                                  PWM4   /*!< Peripheral name */
#define BOARD_INITPWM_M1_PWM_B1_SIGNAL                                         B   /*!< Signal name */
#define BOARD_INITPWM_M1_PWM_B1_CHANNEL                                       1U   /*!< Signal channel */

/* GPIO_EMC_B1_17 (coord E2), M1_PWM_A2 */
/* Routed pin properties */
#define BOARD_INITPWM_M1_PWM_A2_PERIPHERAL                                  PWM4   /*!< Peripheral name */
#define BOARD_INITPWM_M1_PWM_A2_SIGNAL                                         A   /*!< Signal name */
#define BOARD_INITPWM_M1_PWM_A2_CHANNEL                                       2U   /*!< Signal channel */

/* GPIO_EMC_B1_16 (coord H1), M1_PWM_B2 */
/* Routed pin properties */
#define BOARD_INITPWM_M1_PWM_B2_PERIPHERAL                                  PWM4   /*!< Peripheral name */
#define BOARD_INITPWM_M1_PWM_B2_SIGNAL                                         B   /*!< Signal name */
#define BOARD_INITPWM_M1_PWM_B2_CHANNEL                                       2U   /*!< Signal channel */

/* GPIO_EMC_B1_18 (coord D1), M2_PWM_A0 */
/* Routed pin properties */
#define BOARD_INITPWM_M2_PWM_A0_PERIPHERAL                                  PWM2   /*!< Peripheral name */
#define BOARD_INITPWM_M2_PWM_A0_SIGNAL                                         A   /*!< Signal name */
#define BOARD_INITPWM_M2_PWM_A0_CHANNEL                                       0U   /*!< Signal channel */

/* GPIO_EMC_B1_19 (coord F4), M2_PWM_B0 */
/* Routed pin properties */
#define BOARD_INITPWM_M2_PWM_B0_PERIPHERAL                                  PWM2   /*!< Peripheral name */
#define BOARD_INITPWM_M2_PWM_B0_SIGNAL                                         B   /*!< Signal name */
#define BOARD_INITPWM_M2_PWM_B0_CHANNEL                                       0U   /*!< Signal channel */

/* GPIO_EMC_B1_20 (coord G1), M2_PWM_A1 */
/* Routed pin properties */
#define BOARD_INITPWM_M2_PWM_A1_PERIPHERAL                                  PWM2   /*!< Peripheral name */
#define BOARD_INITPWM_M2_PWM_A1_SIGNAL                                         A   /*!< Signal name */
#define BOARD_INITPWM_M2_PWM_A1_CHANNEL                                       1U   /*!< Signal channel */

/* GPIO_EMC_B1_21 (coord K4), M2_PWM_B1 */
/* Routed pin properties */
#define BOARD_INITPWM_M2_PWM_B1_PERIPHERAL                                  PWM2   /*!< Peripheral name */
#define BOARD_INITPWM_M2_PWM_B1_SIGNAL                                         B   /*!< Signal name */
#define BOARD_INITPWM_M2_PWM_B1_CHANNEL                                       1U   /*!< Signal channel */

/* GPIO_EMC_B1_23 (coord F1), M2_PWM_A2 */
/* Routed pin properties */
#define BOARD_INITPWM_M2_PWM_A2_PERIPHERAL                                  PWM2   /*!< Peripheral name */
#define BOARD_INITPWM_M2_PWM_A2_SIGNAL                                         A   /*!< Signal name */
#define BOARD_INITPWM_M2_PWM_A2_CHANNEL                                       2U   /*!< Signal channel */

/* GPIO_EMC_B1_22 (coord L3), M2_PWM_B2 */
/* Routed pin properties */
#define BOARD_INITPWM_M2_PWM_B2_PERIPHERAL                                  PWM2   /*!< Peripheral name */
#define BOARD_INITPWM_M2_PWM_B2_SIGNAL                                         B   /*!< Signal name */
#define BOARD_INITPWM_M2_PWM_B2_CHANNEL                                       2U   /*!< Signal channel */

/* GPIO_EMC_B1_00 (coord H3), M1_FAULT_OV */
/* Routed pin properties */
#define BOARD_INITPWM_M1_FAULT_OV_PERIPHERAL                                PWM4   /*!< Peripheral name */
#define BOARD_INITPWM_M1_FAULT_OV_SIGNAL                                   FAULT   /*!< Signal name */
#define BOARD_INITPWM_M1_FAULT_OV_CHANNEL                                     0U   /*!< Signal channel */

/* GPIO_EMC_B1_01 (coord H4), M1_FAULT_OC */
/* Routed pin properties */
#define BOARD_INITPWM_M1_FAULT_OC_PERIPHERAL                                PWM4   /*!< Peripheral name */
#define BOARD_INITPWM_M1_FAULT_OC_SIGNAL                                   FAULT   /*!< Signal name */
#define BOARD_INITPWM_M1_FAULT_OC_CHANNEL                                     1U   /*!< Signal channel */

/* GPIO_EMC_B1_26 (coord N4), M1_FAULT_OT */
/* Routed pin properties */
#define BOARD_INITPWM_M1_FAULT_OT_PERIPHERAL                                PWM4   /*!< Peripheral name */
#define BOARD_INITPWM_M1_FAULT_OT_SIGNAL                                   FAULT   /*!< Signal name */
#define BOARD_INITPWM_M1_FAULT_OT_CHANNEL                                     2U   /*!< Signal channel */

/* GPIO_EMC_B1_04 (coord J4), M2_FAULT_OV */
/* Routed pin properties */
#define BOARD_INITPWM_M2_FAULT_OV_PERIPHERAL                                PWM2   /*!< Peripheral name */
#define BOARD_INITPWM_M2_FAULT_OV_SIGNAL                                   FAULT   /*!< Signal name */
#define BOARD_INITPWM_M2_FAULT_OV_CHANNEL                                     0U   /*!< Signal channel */

/* GPIO_EMC_B1_05 (coord H6), M2_FAULT_OC */
/* Routed pin properties */
#define BOARD_INITPWM_M2_FAULT_OC_PERIPHERAL                                PWM2   /*!< Peripheral name */
#define BOARD_INITPWM_M2_FAULT_OC_SIGNAL                                   FAULT   /*!< Signal name */
#define BOARD_INITPWM_M2_FAULT_OC_CHANNEL                                     1U   /*!< Signal channel */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPWM(void);                     /* Function assigned for the Cortex-M7F */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLPUART(void);                  /* Function assigned for the Cortex-M7F */

#define XBAR_DIR_CTRL1_IOMUXC_XBAR_DIR_SEL_12_IOMUX 0x00U /*!< IOMUXC XBAR_INOUT12 function direction select: XBAR_INOUT as input */
#define XBAR_DIR_CTRL1_IOMUXC_XBAR_DIR_SEL_13_IOMUX 0x00U /*!< IOMUXC XBAR_INOUT13 function direction select: XBAR_INOUT as input */
#define XBAR_DIR_CTRL1_IOMUXC_XBAR_DIR_SEL_20_IOMUX 0x00U /*!< IOMUXC XBAR_INOUT20 function direction select: XBAR_INOUT as input */
#define XBAR_DIR_CTRL1_IOMUXC_XBAR_DIR_SEL_21_IOMUX 0x00U /*!< IOMUXC XBAR_INOUT21 function direction select: XBAR_INOUT as input */
#define XBAR_DIR_CTRL1_IOMUXC_XBAR_DIR_SEL_22_IOMUX 0x00U /*!< IOMUXC XBAR_INOUT22 function direction select: XBAR_INOUT as input */
#define XBAR_DIR_CTRL1_IOMUXC_XBAR_DIR_SEL_23_IOMUX 0x00U /*!< IOMUXC XBAR_INOUT23 function direction select: XBAR_INOUT as input */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitENC(void);                     /* Function assigned for the Cortex-M7F */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitCMP(void);                     /* Function assigned for the Cortex-M7F */

/* GPIO_SD_B1_04 (coord B15), M1_GD3000_RESET */
/* Routed pin properties */
#define BOARD_INITLPSPI3_M1_GD3000_RESET_PERIPHERAL                       RGPIO5   /*!< Peripheral name */
#define BOARD_INITLPSPI3_M1_GD3000_RESET_SIGNAL                          gpio_io   /*!< Signal name */
#define BOARD_INITLPSPI3_M1_GD3000_RESET_CHANNEL                              8U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLPSPI3_M1_GD3000_RESET_GPIO                             RGPIO5   /*!< GPIO peripheral base pointer */
#define BOARD_INITLPSPI3_M1_GD3000_RESET_GPIO_PIN                             8U   /*!< GPIO pin number */
#define BOARD_INITLPSPI3_M1_GD3000_RESET_GPIO_PIN_MASK                (1U << 8U)   /*!< GPIO pin mask */

/* GPIO_SD_B1_05 (coord A16), M1_GD3000_EN */
/* Routed pin properties */
#define BOARD_INITLPSPI3_M1_GD3000_EN_PERIPHERAL                          RGPIO5   /*!< Peripheral name */
#define BOARD_INITLPSPI3_M1_GD3000_EN_SIGNAL                             gpio_io   /*!< Signal name */
#define BOARD_INITLPSPI3_M1_GD3000_EN_CHANNEL                                 9U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLPSPI3_M1_GD3000_EN_GPIO                                RGPIO5   /*!< GPIO peripheral base pointer */
#define BOARD_INITLPSPI3_M1_GD3000_EN_GPIO_PIN                                9U   /*!< GPIO pin number */
#define BOARD_INITLPSPI3_M1_GD3000_EN_GPIO_PIN_MASK                   (1U << 9U)   /*!< GPIO pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLPSPI3(void);                  /* Function assigned for the Cortex-M7F */

/* GPIO_AON_19 (coord D5), M2_GD3000_RESET */
/* Routed pin properties */
#define BOARD_INITLPSPI2_M2_GD3000_RESET_PERIPHERAL                       RGPIO1   /*!< Peripheral name */
#define BOARD_INITLPSPI2_M2_GD3000_RESET_SIGNAL                          gpio_io   /*!< Signal name */
#define BOARD_INITLPSPI2_M2_GD3000_RESET_CHANNEL                             19U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLPSPI2_M2_GD3000_RESET_GPIO                             RGPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITLPSPI2_M2_GD3000_RESET_GPIO_PIN                            19U   /*!< GPIO pin number */
#define BOARD_INITLPSPI2_M2_GD3000_RESET_GPIO_PIN_MASK               (1U << 19U)   /*!< GPIO pin mask */

/* GPIO_AON_20 (coord E5), M2_GD3000_EN */
/* Routed pin properties */
#define BOARD_INITLPSPI2_M2_GD3000_EN_PERIPHERAL                          RGPIO1   /*!< Peripheral name */
#define BOARD_INITLPSPI2_M2_GD3000_EN_SIGNAL                             gpio_io   /*!< Signal name */
#define BOARD_INITLPSPI2_M2_GD3000_EN_CHANNEL                                20U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLPSPI2_M2_GD3000_EN_GPIO                                RGPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITLPSPI2_M2_GD3000_EN_GPIO_PIN                               20U   /*!< GPIO pin number */
#define BOARD_INITLPSPI2_M2_GD3000_EN_GPIO_PIN_MASK                  (1U << 20U)   /*!< GPIO pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLPSPI2(void);                  /* Function assigned for the Cortex-M7F */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void SINC_Motor1(void);                       /* Function assigned for the Cortex-M7F */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void SINC_Motor2(void);                       /* Function assigned for the Cortex-M7F */

/* GPIO_EMC_B1_10 (coord E3), M1_485 */
/* Routed pin properties */
#define BOARD_UART5_M1_485_PERIPHERAL                                     RGPIO2   /*!< Peripheral name */
#define BOARD_UART5_M1_485_SIGNAL                                        gpio_io   /*!< Signal name */
#define BOARD_UART5_M1_485_CHANNEL                                           10U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_UART5_M1_485_GPIO                                           RGPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_UART5_M1_485_GPIO_PIN                                          10U   /*!< GPIO pin number */
#define BOARD_UART5_M1_485_GPIO_PIN_MASK                             (1U << 10U)   /*!< GPIO pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_UART5(void);                       /* Function assigned for the Cortex-M7F */

/* GPIO_EMC_B1_11 (coord F2), M2_485 */
/* Routed pin properties */
#define BOARD_UART8_M2_485_PERIPHERAL                                     RGPIO2   /*!< Peripheral name */
#define BOARD_UART8_M2_485_SIGNAL                                        gpio_io   /*!< Signal name */
#define BOARD_UART8_M2_485_CHANNEL                                           11U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_UART8_M2_485_GPIO                                           RGPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_UART8_M2_485_GPIO_PIN                                          11U   /*!< GPIO pin number */
#define BOARD_UART8_M2_485_GPIO_PIN_MASK                             (1U << 11U)   /*!< GPIO pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_UART8(void);                       /* Function assigned for the Cortex-M7F */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void M7_DebugConsole(void);                   /* Function assigned for the Cortex-M7F */

#define QTIMER_CTRL1_QTIMER1_TMR0_INPUT_SEL_XBAR 0x01U /*!< QTIMER1 TMR0 input select: Input from XBAR */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void SLOWLOOP_TRIGGER(void);                  /* Function assigned for the Cortex-M7F */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
